# Site settings
title: Rackspace Container Service
description: >
  Rackspace-backed containers as a service, making development,
  testing, and deployment of Docker-powered applications hassle-free.

baseurl: "" # the subpath of your site, e.g. /blog/

# Things like RSS feeds need absolute URLs, not root-relative
absolute_base_url: https://getcarina.com
# Build settings
markdown: redcarpet

encoding: UTF-8

redcarpet:
  extensions: ["with_toc_data"]

exclude:
  - script
  - Gemfile
  - Gemfile.lock
  - package.json

gems:
  - jekyll-paginate

deconst_categories:
  - getcarina.com

paginate: 10
paginate_path: /blog/page/:num
excerpt_separator: "<!-- more -->"
permalink: /blog/:title/

gravatar:
  default: mm
  secure: true
  size: 80

collections:
  concepts:
    output: true
    permalink: /docs/concepts/:title/
    label: concepts
  ecosystem:
    output: true
    permalink: /docs/ecosystem/:title/
    label: ecosystem
  getting-started:
    output: true
    permalink: /docs/getting-started/:title/
    label: getting-started
  reference:
    output: true
    permalink: /docs/reference/:title/
    label: reference
  troubleshooting:
    output: true
    permalink: /docs/troubleshooting/:title/
    label: troubleshooting
  tutorials:
    output: true
    permalink: /docs/tutorials/:title/
    label: tutorials

defaults:
  -
    scope:
      path: "docs"
    values:
      layout: "plain"

assets:
  sources:
  - _assets/img
